services:
  - type: web
    name: photo-gallery-app
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: photo-gallery-app
          property: port
      - key: NOTION_INTEGRATION_SECRET
        sync: false
      - key: NOTION_PAGE_URL
        sync: false
      - key: SESSION_SECRET
        generateValue: true